version: '3.7'

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  client_mobile:
    container_name: client_mobile
    build:
      context: mobile_front
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - area:/mobile_app/

  client_web:
    container_name: client_web
    build:
      context: client_web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - server
      - client_mobile
    volumes:
      - area:/mobile_app/

volumes:
  area:
