version: '3.7'

services:

  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: yarn start

  web:
    container_name: web
    build:
      context: client_web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: yarn start
    depends_on:
      - server