version: '3.7'

services:

  server:
    container_name: sample
    build:
      context: backend_server
      dockerfile: Dockerfile
    ports:
      - 8080
    environment:
      - CHOKIDAR_USEPOLLING=true
