version: '3.7'

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  web:
    container_name: web
    build:
      context: client_web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - server