name: Server-Units-Tests
on: [push, pull_request]
jobs:
  Testing-Launching-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd server && yarn
      - run: yarn test
